name: mix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 27.x
        elixir-version: 1.18.x
    - name: System packages
      run: sudo apt-get install -y cmake build-essential libsnappy-dev
    - name: Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Compilation
      run: mix compile
    - name: Tests
      run: mix test
