name: mix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 28.x
        elixir-version: 1.19.x
    - name: System packages
      run: sudo apt-get install -y cmake build-essential  liblz4-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev build-essential libcsv3 libcsv-dev cmake
    - name: Dependencies
      run: mix deps.get
    - name: Compilation
      run: mix compile

